### PR TITLE
Created template react with tailwind

### PR DESCRIPTION
**Pull request by ferMartz**
Feel free to review the folder template-react-tw

### CODE REVIEW

**Review by MioQuispe — APPROVED** [review]
Thanks for the contribution! Do you want me to add your name to the menu?
As follows:

Javascript
Typescript
JS + Tailwind (by ferMartz)

**Comment by MioQuispe** [comment]
image

Here's how it looks

**Comment by ferMartz** [comment]
Yeah, that would be awesome.

Great repo by the way. Thanks for doing this. Saving me a lot of work. I’m just diving into developing internet computer apps.



Fer Martz

**Comment by MioQuispe** [comment]
> Yeah, that would be awesome. Great repo by the way. Thanks for doing this. Saving me a lot of work. I’m just diving into developing internet computer apps. Fer Martz
> […](#)
> On May 18, 2021, at 2:28 PM, MioQuispe ***@***.***> wrote: ﻿ @MioQuispe approved this pull request. Thanks for the contribution! Do you want me to add your name to the menu? As follows: Javascript Typescript JS + Tailwind (by ferMartz) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Good to hear that. I've published it so it should be there now (if not, clear npx cache with ```rm -rf ~/.npm/_npx```. Thanks again!

**Pull request merged**
